### ISSUE TITLE
sl3 data extraction

### ISSUE THREAD

**Issue by Ezpania** [opensounder/python-sllib#7] opened 2021-08-27 09:13 UTC
I would like to play around with the received signals that are plotted in the echogram, but i am struggling with extracting these from an sl3 file. I tried following your jupyter example for sl2 files, but i have gotten stuck. Any tips?

**Comment by kmpm** [comment] 2021-08-27 14:36
Sl3 format isn't working at the moment. We are still trying to reverse engineer that format.

kmpm
[github/kmpm](https://github.com/kmpm) | [gitlab/kmpm](https://gitlab.com/kmpm)

-------- Originalmeddelande --------
På 27 aug. 2021 11:13, Ezpania skrev:

**Comment by kmpm** [comment] 2021-08-28 18:09
Closing as a duplicate of issue #2

**Closed as completed by kmpm** 2021-08-28 18:09 UTC
Labels: duplicate
